@startuml Constants
class Constants{
static const char *const COMMAND_POOL_FAIL_CREATE_MSG = "Failed to create command pool!";
static const char *const FRAMEBUFFER_CREATE_FAIL_MSG = "Failed to create framebuffer";
static const char *const WINDOW_SURF_CREATE_FAIL_MSG = "Failed to create window surface.";
static const char *const RENDER_PASS_CREATE_FAIL_MSG = "Failed to create render pass!";
static const char *const SWAP_CHAIN_CREATE_FAIL_MSG = "Failed to create swap chain!";
static const char *const LOGI_DEV_CREATE_FAIL_MSG = "Failed to create logical device!";
static const char *const NO_VULK_DEV_AVAILABLE_MSG = "No Vulkan devices available.";
static const char *const VULK_DEV_NOT_SUITABLE_MSG = "No suitable Vulkan devices available.";
static const char *const NO_SUITABLE_MEMORY_MSG = "Failed to find suitable memory type!";
static const char *const PIPELINE_LAYOUT_CREATE_FAIL_MSG = "Failed to create pipeline layout!";
static const char *const PIPELINE_CREATE_FAIL_MSG = "Failed to create graphics pipeline!";
}
@enduml