@startuml


!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml



/' Objects '/

class Model {
	__
	-createImageView(vk::Image image, vk::Format format, vk::ImageAspectFlags aspectFlags, uint32_t inMipLevels) : vk::ImageView
	-createTextureImage() : void
	-createTextureImageView() : void
	-createTextureSampler() : void
	-DestroyBufferIfExists(std::tuple<vk::Buffer, VmaAllocation> buffer) : void
	-loadImageDataToGPU() : void
	-processSceneObject(const aiScene* scene) : void
	-readModelFile(const std::string& pFile) : bool
	..Public Methods..
	+~Model()
	+GetIndexCount() : uint32_t
	+GetIndicesBuffer() : std::tuple<vk::Buffer , VmaAllocation>&
	+GetMeshBuffer() : std::tuple<vk::Buffer , VmaAllocation>&
	+GetModelMatrix() : glm::mat4
	+GetModelTransform() : glm::mat4&
	+GetTextureBuffer() : std::tuple<vk::Image , VmaAllocation>&
	+GetTextureSampler() : vk::Sampler
	+GetTextureView() : vk::ImageView
	+loadDataToGPU() : void
	+Model(const std::string fName, const std::string texFName)
	+Model(const std::string fName)
	+RotateModel(glm::vec3 axis, float theta) : void
	+ScaleModel(glm::vec3 delta) : void
	+TranslateModel(glm::vec3 delta) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/




@enduml
