@startuml


!define DARKGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml



/' Objects '/

class Vertex {
	+texCoord : glm::vec2
	+color : glm::vec3
	+pos : glm::vec3
	+operator<<(std::ostream& os, const Vertex& vertex) : std : : ostream&
	+{static} getAttributeDescriptions() : std::array<vk::VertexInputAttributeDescription , 3>
	+{static} getBindingDescription() : vk::VertexInputBindingDescription
}





/' Inheritance relationships '/




/' Aggregation relationships '/




@enduml
